version: '3'

services:

  ai2020-front:
    image: km2442/prz-stock-trader-front:stable
    restart: always
    container_name: ai2020-front
    ports:
      - 80:80
    networks: 
      - ai2020-network

  ai2020-back:
    image: km2442/prz-stock-trader-back:stable
    restart: always
    container_name: ai2020-back
    networks: 
      - ai2020-network
    ports:
      - 8000:8080
    environment:
      POSTGRES_URL: ai2020-backdb:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      SPRING_PROFILES_ACTIVE: data
      MAX_DB_CONNECTIONS: 96

  ai2020-brick:
    image: km2442/prz-stock-trader-benchmark:stable
    restart: always
    container_name: ai2020-brick
    networks: 
      - ai2020-network
    ports:
      - 9000:8080
    environment:
      POSTGRES_URL: ai2020-brickdb:5432
      POSTGRES_USER: brick
      POSTGRES_PASSWORD: brick
      POSTGRES_DB: postgres
      ALGORITHM_SAVE_INTERVAL: 5000
      ALGORITHM_SAVE_THREADS: 1
      ALGORITHM_SAVE_LIMIT: 100
      ALGORITHM_THREADS_MIN: 256
      ALGORITHM_THREADS_MAX: 512
      ALGORITHM_CORE_THREADS: 8
      STOCK_BACKEND_URL: http://ai2020-back:8080
        
  ai2020-backdb:
    image: postgres:12.4
    restart: always
    container_name: ai2020-backdb
    networks: 
      - ai2020-network
    expose: 
      - 5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./postgres/back:/var/lib/postgresql/data

  ai2020-brickdb:
    image: postgres:alpine
    restart: always
    container_name: ai2020-brickdb
    networks: 
      - ai2020-network
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: brick
      POSTGRES_PASSWORD: brick
    volumes: 
      - ./postgres/brick:/var/lib/postgresql/data

networks:
  ai2020-network:
    driver: bridge