version: '3'

services:

  ai2020-front:
    image: km2442/prz-stock-trader-front:stable
    restart: always
    container_name: ai2020-front
    networks: 
      - ai2020-network

  ai2020-back:
    image: km2442/prz-stock-trader-back:stable
    restart: always
    container_name: ai2020-back
    networks: 
      - ai2020-network
    ports:
      - 8000:8080
    environment:
      POSTGRES_URL: ai2020-backdb:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      SPRING_PROFILES_ACTIVE: data
        
  ai2020-backdb:
    image: postgres:alpine
    restart: always
    container_name: ai2020-backdb
    networks: 
      - ai2020-network
    ports: 
      - 5431:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./postgres/back:/var/lib/postgresql/data

  ai2020-brickdb:
    image: postgres:alpine
    restart: always
    container_name: ai2020-brickdb
    networks: 
      - ai2020-network
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./postgres/brick:/var/lib/postgresql/data

networks:
  ai2020-network:
    driver: bridge